{
 "title": "jetson nano",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "GPU utilizzo percentuale",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "gpu_usage_percentage", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (cpu_usage_percentage) / 4",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU POD USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "gpu_pod_usage", "legendFormat": "{{pod}}{{instance}}" }
   ]
  },
  {
   "title": "Ram usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ram_usage_percentage", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Gpu frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "gpu_utilization_Hz{nvidia_gpu=\"freq\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}